services:

  app-go:
    image: app-go:latest
    ports:
    - 8090:8090
    environment:
      DB_USER=: root
      DB_PASS: harsh
      DB_NAME: student
    depends_on:
    - mysql
    restart: always

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: harsh
      MYSQL_DATABASE: student
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: unless-stopped
